### Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np

### The Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int32')

In [8]:
# Get Size (in bytes)
a.itemsize

4

In [11]:
# Get total size
a.size*a.itemsize

12

In [12]:
# Get total size (via nbytes)
a.nbytes

12

In [10]:
# Get number of elements
a.size

3

In [14]:
# Get number of elements
b.size

6

In [17]:
# Question
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


### Accessing/Changing specific elements, rows, columns, etc

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
# Get a specific element [r, c]
a[1, 5]

np.int64(13)

In [20]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# Get a specific column
a[:, 2]

array([1, 2])

In [29]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [31]:
a[1,5] = 20
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [36]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


**3-d example**

In [27]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [41]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [53]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)
print("-----------------")
a[:,2]=20
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-----------------
[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]


### Initializing Different Types of Arrays

In [54]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [56]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [57]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [59]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.84940473, 0.93077068],
       [0.66100773, 0.8915859 ],
       [0.87421647, 0.5008377 ],
       [0.93688789, 0.41925398]])

In [60]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 4, -3,  2],
       [ 5, -2,  4],
       [ 1,  6,  6]], dtype=int32)

In [63]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# Repeat an array
arr = np.array([[1,2,3]])
print(arr)
print("----------")
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]]
----------
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
output = np.ones((5,5))
print(output)
print("----------")

z = np.zeros((3,3))
z[1,1] = 9
print(z)
print("----------")

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----------
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
----------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
# Question
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


#### Array Copying Warning!

In [82]:
a = np.array([1,2,3]) # [1,2,3]
b = a.copy() # B is a distinct .copy() of A 
b[0] = 100
print("b=a.copy() ... b is distinct")
print(a)
print("--------")
print(b)
print("--------")
print("--------")
print("c=a .... c is not distinct (c 'points' to a)")
c = a
c[1]=100
print(a)
print("--------")
print(c)

b=a.copy() ... b is distinct
[1 2 3]
--------
[100   2   3]
--------
--------
c=a .... c is not distinct (c 'points' to a)
[  1 100   3]
--------
[  1 100   3]


#### How can we programtically build this 2d array?
<img src="./want-this-2d-array.png" alt="wanted 2d array" width=200 height=200>

In [72]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
z=np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [75]:
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [78]:
output[1:4,1:4]=z
print(output)
print("--------")
output[1:-1,1:-1]=z # from start to finish (minus index)
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
--------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematics with Numpy

In [83]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [84]:
a + 2

array([3, 4, 5, 6])

In [85]:
a - 2

array([-1,  0,  1,  2])

In [86]:
a * 2

array([2, 4, 6, 8])

In [87]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [88]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [89]:
a ** 2

array([ 1,  4,  9, 16])

In [95]:
# Take the sin
s=np.sin(a)
print(s)
print("-----------")
c=np.cos(a)
print(c)


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
-----------
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [96]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [97]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [98]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [99]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [100]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.min(stats)

np.int64(1)

In [102]:
np.max(stats, axis=1)

array([3, 6])

In [103]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [104]:
# Question
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
print(b)

15


### Reorganizing Arrays

In [151]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [158]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [179]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [196]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])